### PR TITLE
Misc. code cleanup and review 

### PR DESCRIPTION
**Pull request by PierreLvx**

### CODE REVIEW

**Comment by Marginal** [comment]
Thanks - there's certainly evidence of "my first Python program" in the codebase!
I've pushed the backlog from my working tree. Any chance you can resolve the conflicts?

**Comment by PierreLvx** [comment]
@Marginal Sure! I'll have a look tonight :)

**Comment by PierreLvx** [comment]
Done!

**Comment by Marginal** [comment]
Thanks

**Pull request merged**
