### PR TITLE
Improved conformance to PEP 8 guidelines.

### PR DESCRIPTION
**Pull request by PierreLvx**
A number of rules are ignored for now (see the Travis configuration file). This PR does:
- Remove trailing whitespace ;
- Make indentation consistent (no more mixes of tabs and spaces) ;
- Make sure there is proper whitespace around modulo and bitwise operators ;
- Replaces uses of `has_key()` with `in` (see http://stackoverflow.com/questions/1323410/has-key-or-in).

Travis is still failing because there's some work left to be done (see https://travis-ci.org/PierreLvx/FS2XPlane). All in due time :)

### CODE REVIEW

**Comment by PierreLvx** [comment]
`not in`are now taken care of. E721 is the only remaining warning now.

**Comment by PierreLvx** [comment]
[Now passing all the checks](https://travis-ci.org/PierreLvx/FS2XPlane).

**Comment by Marginal** [comment]
I'm afraid that I don't see PEP8 compliance as being a particularly important goal for **existing** code for two reasons:
1. Achieving slavish PEP8 compliance can harm readability - e.g. by breaking column alignment of values in a matrix or of successive inline comments. PEP8 itself recognises this: "know when to be inconsistent".
2. Any non-functional changes to a codebase pollute the blame history. I don't think that marginal improvements to readability (e.g. spaces around binary operators, "not in") or invisible changes (e.g. removing trailing whitespace) are worth obscuring the blame history to this extent.

(Also a minor point: According to PEP8 Python 2 files should be ASCII, and ASCII files should not contain an encoding declaration. Python 2 helpfully warns at runtime if it finds a non-ASCII character).

**Comment by PierreLvx** [comment]
I very much agree with that, and that's why I turned off many warnings. However:
- Different editors handle trailing whitespace differently. Mine for instance is set to trim it. Mixed indentation can be a pain (+ only spaces translate reliably across platforms/editors). Seeing that you share the source and welcome contributions, you may want to standardize everything once and for all.
- Binary operators with no whitespace around them really _aren't_ easy on the eyes (at a quick glance `foo&bar` can look like a single word).

> Any non-functional changes to a codebase pollute the blame history.

I beg to differ. IMHO, part of maintaining a codebase is keeping it lean, clean, and consistent.

**Comment by Marginal** [comment]
> Different editors handle trailing whitespace differently. Mine for instance is set to trim it.

The main (sole?) reason to have a policy of no trailing whitespace is to avoid noise in the commit log. So configuring your editor like this is a bad idea when used with "unclean" files since it defeats the _whole point_ of the policy.
If using Emacs I'd recommend [ws-butler](https://github.com/lewang/ws-butler) or the older [ws-trim](http://ftp.lysator.liu.se/pub/emacs/ws-trim.el) (which I use), both of which by default only trim lines that you've actually edited. I assume that other editors have a similar capability. Alternatively, consider a Git pre-commit hook.

> Binary operators with no whitespace around them really aren't easy on the eyes

I agree. But I also find `git blame` useful when debugging a regression or just trying to work out why a piece of code is written the way that it is. I just don't think it's worth sacrificing the usability of the commit history for d19e689 etc.

**Pull request closed without merging**
